// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvfiicqglrlealnirfvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52ZmlpY3FnbHJsZWFsbmlyZnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDk3NjUsImV4cCI6MjA2NjAyNTc2NX0.OyH2j1V6zTIw_ja4uetKXzkOLfzSECWL4f1EAUsMXbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);